### ISSUE TITLE
How to share req.user in all view html template

### ISSUE THREAD

**Issue by vuongnv-0085** [TrejGun/session-based-rest-authorization-for-nestjs#96]
Hello, I have a question:
How to share req.user in all view html template ? 
If each controller must to return { user: req.user }, it is so much effort.

Thanks you

**Comment by TrejGun** [comment]
as you can see i dont use any template engine. in fact all my nestjs servers acts only like api. then on front end i do a request to `/login` endpoing and store received user on localstorage while cookies or jwt token is being send with each request
